"""Acceptance-policy generation and gating (domain design §2).

**No acceptance policy, no verdict.** A submission that does not declare what
would count as valid gets a domain-default policy generated from its endpoint
and assay type, marked `source: generated` so it is never mistaken for the
submitter's own bar. The user can see it and tighten it.

Defaults are deliberately conservative and domain-specific: the failure modes
this field actually has (scaffold leakage, analog leakage, split-parity
mismatch, threshold tuned on test) are the ones the defaults gate on. Where a
default is a judgement call rather than a rule, it is recorded in `notes` so the
generated policy explains itself.
"""

from __future__ import annotations

from .schema import (
    AcceptancePolicy,
    AssayType,
    Claim,
    ClaimType,
    DedupPolicy,
    PolicySource,
    SplitMethod,
)

# Endpoints where near-duplicate analogs are especially likely to survive a
# nominal scaffold split, so the analog-leakage bar is tightened.
_ANALOG_SENSITIVE_HINTS = ("bioactivity", "binding", "affinity", "ic50", "ki", "ec50", "qsar")


def _is_analog_sensitive(endpoint: str | None) -> bool:
    low = (endpoint or "").lower()
    return any(h in low for h in _ANALOG_SENSITIVE_HINTS)


def default_policy(
    assay_type: AssayType = AssayType.UNKNOWN,
    endpoint: str | None = None,
    split_method: SplitMethod = SplitMethod.UNKNOWN,
    claim_type: ClaimType = ClaimType.COMPARATIVE,
) -> AcceptancePolicy:
    """Generate the domain-default acceptance policy for an endpoint type.

    The ADMET-classification defaults from the design are the base; regression
    and bioactivity endpoints adjust from there.
    """
    notes: list[str] = ["generated by intake; review and tighten before relying on the verdict"]

    # Comparative claims need seeds to test a margin; a pure reproduction claim
    # needs fewer, since it is checked against a fixed reported number.
    min_seeds = 5 if claim_type in (ClaimType.COMPARATIVE, ClaimType.ABLATION,
                                    ClaimType.RANKING) else 3

    dedup = DedupPolicy()
    if _is_analog_sensitive(endpoint):
        dedup = DedupPolicy(analog_tanimoto=0.6, max_analog_fraction=0.02)
        notes.append("analog threshold tightened to 0.6: bioactivity-style endpoint")

    # AUROC-vs-AUPRC only makes sense as a gate for classification.
    metric_balance = assay_type in (
        AssayType.BINARY_CLASSIFICATION,
        AssayType.MULTICLASS_CLASSIFICATION,
        AssayType.UNKNOWN,
    )

    # A claimed scaffold/temporal split is a promise the verifiers can check; an
    # unknown split method is itself a finding, so parity is required regardless.
    if split_method is SplitMethod.UNKNOWN:
        notes.append("split method not stated: claimed_split_is_actual will report can't-tell")

    return AcceptancePolicy(
        source=PolicySource.GENERATED,
        min_seeds=min_seeds,
        ci_level=0.95,
        alpha=0.05,
        require_split_parity=True,
        require_test_isolation=True,
        require_dataset_hash=True,
        require_dedup=dedup,
        metric_appropriate_for_balance=metric_balance,
        require_baseline_same_data=True,
        # Applicability domain is high-value but soft; off by default so it
        # raises caveats rather than blocking, per domain design §4.6.
        require_applicability_domain=False,
        notes="; ".join(notes),
    )


def policy_for_claim(claim: Claim) -> AcceptancePolicy:
    """Domain-default policy derived from a claim's own context."""
    return default_policy(
        assay_type=claim.context.assay_type,
        endpoint=claim.context.endpoint,
        split_method=claim.context.split.method,
        claim_type=claim.type,
    )


def ensure_policy(claim: Claim) -> Claim:
    """Attach a generated policy if the claim has none. Returns a new Claim;
    an authored policy is never overwritten."""
    if claim.acceptance_policy is not None:
        return claim
    return claim.model_copy(update={"acceptance_policy": policy_for_claim(claim)})


def ensure_policies(claims: list[Claim]) -> list[Claim]:
    return [ensure_policy(c) for c in claims]


def describe(policy: AcceptancePolicy) -> list[str]:
    """Human-readable rendering of the constraints — what the CLI prints and
    what a reviewer reads before agreeing to the bar."""
    d = policy.require_dedup
    lines = [
        f"source:              {policy.source.value}",
        f"min seeds:           {policy.min_seeds}",
        f"significance:        alpha={policy.alpha}, CI={policy.ci_level}",
        f"split parity:        {'required' if policy.require_split_parity else 'not required'}",
        f"test isolation:      {'required' if policy.require_test_isolation else 'not required'}",
        f"dataset hash pinned: {'required' if policy.require_dataset_hash else 'not required'}",
        f"dedup:               exact={d.exact} stereo/salt={d.stereo_salt} "
        f"analog_tanimoto={d.analog_tanimoto} max_frac={d.max_analog_fraction}",
        f"metric vs balance:   {'checked' if policy.metric_appropriate_for_balance else 'skipped'}",
        f"baseline same data:  "
        f"{'required' if policy.require_baseline_same_data else 'not required'}",
        f"applicability dom.:  "
        f"{'required' if policy.require_applicability_domain else 'advisory'}",
    ]
    if policy.notes:
        lines.append(f"notes:               {policy.notes}")
    return lines
