"""The typed Claim — the central object (domain design §2).

Everything hangs off a Claim, not a run or a repo. A claim compiles into a set
of *evidence requirements*, and the validity verifiers exist to satisfy or refute
each requirement. This is the object intake produces and the adjudicator
consumes.

Three things are separated deliberately (domain design §1), because the remedy
and the consequence differ per layer:

  1. computational reproducibility — same code+data+seed -> same number
  2. methodological validity       — the number came from a sound evaluation
  3. claim support                 — the sentence is entailed by the valid number

The AcceptancePolicy in this module is layer (2)+(3): the constraints and
requirements that MUST hold for a VALID verdict. Design rule, mirroring "no
positive control, no verdict": **no acceptance policy, no verdict.**
"""

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, Field


# --- closed vocabularies ------------------------------------------------------


class ClaimType(str, Enum):
    """What kind of assertion is being made (domain design §2)."""

    COMPARATIVE = "comparative_performance"
    REPRODUCTION = "reproduction"
    ABSOLUTE = "absolute"
    RANKING = "ranking"
    ABLATION = "ablation"


class Relation(str, Enum):
    OUTPERFORMS = "outperforms"
    ACHIEVES = "achieves"
    RANKS_ABOVE = "ranks_above"
    IS_ROBUST_TO = "is_robust_to"


class AssayType(str, Enum):
    BINARY_CLASSIFICATION = "binary_classification"
    MULTICLASS_CLASSIFICATION = "multiclass_classification"
    REGRESSION = "regression"
    RANKING = "ranking"
    UNKNOWN = "unknown"


class SplitMethod(str, Enum):
    """How train/val/test were separated. `scaffold` and `temporal` carry extra
    obligations the verifiers check (Bemis-Murcko disjointness, time ordering)."""

    RANDOM = "random"
    SCAFFOLD = "scaffold"
    TEMPORAL = "temporal"
    CLUSTER = "cluster"
    PREDEFINED = "predefined"
    UNKNOWN = "unknown"


class PolicySource(str, Enum):
    """Whether the acceptance policy came from the submitter or was generated by
    intake. Generated policies are visible and tightenable by the user."""

    AUTHORED = "authored"
    GENERATED = "generated"


class EvidenceRequirement(str, Enum):
    """The requirements a claim compiles into. Each maps to one or more
    verifiers in the Domain Validity Engine (domain design §4). Keeping this
    closed is what lets the adjudicator reason over requirements rather than
    over free text."""

    # data integrity (§4.1)
    NO_EXACT_DUPLICATES = "no_exact_duplicates"
    NO_STEREO_SALT_DUPLICATES = "no_stereo_salt_duplicates"
    NO_ANALOG_LEAKAGE = "no_analog_leakage"
    LABEL_CONSISTENCY = "label_consistency"
    DATASET_HASH_PINNED = "dataset_hash_pinned"
    # split methodology (§4.2)
    SPLIT_PARITY = "split_parity"
    CLAIMED_SPLIT_IS_ACTUAL = "claimed_split_is_actual"
    SCAFFOLD_SPLIT_INTEGRITY = "scaffold_split_integrity"
    TEMPORAL_SPLIT_VALID = "temporal_split_valid"
    PREPROCESSING_FIT_ON_TRAIN_ONLY = "preprocessing_fit_on_train_only"
    # metric & evaluation (§4.3)
    METRIC_COMPUTED_ON_TEST = "metric_computed_on_test"
    METRIC_MATCHES_CLAIM = "metric_matches_claim"
    METRIC_APPROPRIATE_FOR_BALANCE = "metric_appropriate_for_balance"
    THRESHOLD_NOT_TUNED_ON_TEST = "threshold_not_tuned_on_test"
    METRIC_IMPLEMENTATION_CORRECT = "metric_implementation_correct"
    # statistical support (§4.4)
    SEEDS_SUFFICIENT = "seeds_sufficient"
    MARGIN_SURVIVES_VARIANCE = "margin_survives_variance"
    VARIANCE_REPORTED = "variance_reported"
    # baseline fairness (§4.5)
    BASELINE_EFFORT_PARITY = "baseline_effort_parity"
    BASELINE_SAME_DATA = "baseline_same_data"
    # applicability domain (§4.6)
    TEST_IN_DOMAIN = "test_in_domain"
    ENDPOINT_SCOPE_MATCHES_CLAIM = "endpoint_scope_matches_claim"


# --- claim components ---------------------------------------------------------


class SourceRef(BaseModel):
    """Where in the paper/report this came from. Every extracted field carries
    provenance so a low-confidence claim can be reviewed before anything runs."""

    location: str = Field(..., description="e.g. 'Table 2, p.5' or 'Abstract'")
    quote: str | None = Field(default=None, description="short supporting snippet")


class Margin(BaseModel):
    metric: str = Field(..., description="e.g. 'AUROC'")
    delta: float | None = Field(
        default=None, description="claimed improvement over the comparator"
    )


class Statement(BaseModel):
    """The sentence, typed. `comparator` is required for comparative/ranking
    claims — that is enforced by Claim's validation, not here."""

    subject: str = Field(..., description="the method being claimed for, e.g. 'GNN model X'")
    relation: Relation = Relation.OUTPERFORMS
    comparator: str | None = Field(default=None, description="e.g. 'Random Forest baseline'")
    margin: Margin | None = None
    text: str | None = Field(default=None, description="the verbatim sentence, if available")


class DatasetRef(BaseModel):
    name: str = Field(..., description="e.g. 'TDC/CYP2D6_Veith'")
    version: str | None = None
    hash: str | None = Field(default=None, description="filled at intake; pinning is a requirement")
    url: str | None = None


class SplitSpec(BaseModel):
    method: SplitMethod = SplitMethod.UNKNOWN
    ratio: list[float] = Field(default_factory=list, description="e.g. [0.7, 0.1, 0.2]")
    seed: int | None = None
    date_field: str | None = Field(
        default=None, description="TEMPORAL only: the column holding assay/publication date"
    )


class Representation(BaseModel):
    featurizer: str | None = Field(default=None, description="e.g. 'morgan_r2_2048'")
    notes: str | None = None


class ClaimContext(BaseModel):
    """Everything needed to know *what was measured, on what, how split*. The
    split is the highest-yield object here: split parity and claimed-vs-actual
    are the top invalidators in this field (domain design §4.2)."""

    endpoint: str | None = Field(default=None, description="e.g. 'CYP2D6_inhibition'")
    assay_type: AssayType = AssayType.UNKNOWN
    dataset: DatasetRef | None = None
    split: SplitSpec = Field(default_factory=SplitSpec)
    representation: Representation = Field(default_factory=Representation)


class ReportedValues(BaseModel):
    subject_value: float | None = None
    comparator_value: float | None = None
    metric: str | None = Field(default=None, description="metric the values are in")
    per_seed: dict[str, list[float]] = Field(
        default_factory=dict,
        description="variable -> per-seed values when the paper reports them",
    )
    variance_reported: bool = False


# --- the constraints / requirements object ------------------------------------


class DedupPolicy(BaseModel):
    """Which notions of 'duplicate' must be checked across train/test."""

    exact: bool = True
    stereo_salt: bool = True
    analog_tanimoto: float | None = Field(
        default=0.7,
        ge=0.0,
        le=1.0,
        description="max Morgan-r2 Tanimoto to train allowed for a test molecule; None disables",
    )
    max_analog_fraction: float = Field(
        default=0.05,
        ge=0.0,
        le=1.0,
        description="fraction of test molecules allowed above the Tanimoto threshold",
    )


class AcceptancePolicy(BaseModel):
    """What MUST be true for a VALID verdict — the constraints and requirements.

    Authored by the submitter or generated by intake from the endpoint/assay
    type. `source` records which, so a generated policy is never mistaken for
    the submitter's own bar. Every field here is a gate the adjudicator reads;
    nothing is advisory unless a verifier is itself advisory.
    """

    source: PolicySource = PolicySource.AUTHORED
    min_seeds: int = Field(5, ge=1, description="distinct seeds required for a comparative claim")
    ci_level: float = Field(0.95, gt=0.0, lt=1.0)
    alpha: float = Field(0.05, gt=0.0, lt=1.0, description="significance level for the margin test")
    require_split_parity: bool = Field(
        True, description="subject and comparator evaluated on the identical split"
    )
    require_test_isolation: bool = Field(
        True, description="no test data in training/fitting/threshold selection"
    )
    require_dataset_hash: bool = Field(True, description="the data used hashes to a pinned version")
    require_dedup: DedupPolicy = Field(default_factory=DedupPolicy)
    metric_appropriate_for_balance: bool = Field(
        True, description="flag AUROC on severe imbalance where AUPRC is the honest metric"
    )
    require_baseline_same_data: bool = True
    require_applicability_domain: bool = Field(
        False, description="test molecules must sit inside the training chemistry's domain"
    )
    notes: str | None = None

    def requirements(self, claim: "Claim") -> list[EvidenceRequirement]:
        """Compile this policy + a claim into the evidence requirements that must
        be satisfied. This is the bridge from 'policy as data' to 'verifiers to
        run', and it is deterministic — no model decides what must be checked."""
        req: list[EvidenceRequirement] = []
        d = self.require_dedup
        if d.exact:
            req.append(EvidenceRequirement.NO_EXACT_DUPLICATES)
        if d.stereo_salt:
            req.append(EvidenceRequirement.NO_STEREO_SALT_DUPLICATES)
        if d.analog_tanimoto is not None:
            req.append(EvidenceRequirement.NO_ANALOG_LEAKAGE)
        req.append(EvidenceRequirement.LABEL_CONSISTENCY)
        if self.require_dataset_hash:
            req.append(EvidenceRequirement.DATASET_HASH_PINNED)

        if self.require_split_parity and claim.is_comparative:
            req.append(EvidenceRequirement.SPLIT_PARITY)
        req.append(EvidenceRequirement.CLAIMED_SPLIT_IS_ACTUAL)
        if claim.context.split.method is SplitMethod.SCAFFOLD:
            req.append(EvidenceRequirement.SCAFFOLD_SPLIT_INTEGRITY)
        if claim.context.split.method is SplitMethod.TEMPORAL:
            req.append(EvidenceRequirement.TEMPORAL_SPLIT_VALID)
        if self.require_test_isolation:
            req += [
                EvidenceRequirement.PREPROCESSING_FIT_ON_TRAIN_ONLY,
                EvidenceRequirement.THRESHOLD_NOT_TUNED_ON_TEST,
                EvidenceRequirement.METRIC_COMPUTED_ON_TEST,
            ]

        req += [
            EvidenceRequirement.METRIC_MATCHES_CLAIM,
            EvidenceRequirement.METRIC_IMPLEMENTATION_CORRECT,
        ]
        if self.metric_appropriate_for_balance:
            req.append(EvidenceRequirement.METRIC_APPROPRIATE_FOR_BALANCE)

        req.append(EvidenceRequirement.SEEDS_SUFFICIENT)
        req.append(EvidenceRequirement.VARIANCE_REPORTED)
        if claim.is_comparative:
            req.append(EvidenceRequirement.MARGIN_SURVIVES_VARIANCE)
            req.append(EvidenceRequirement.BASELINE_EFFORT_PARITY)
            if self.require_baseline_same_data:
                req.append(EvidenceRequirement.BASELINE_SAME_DATA)

        if self.require_applicability_domain:
            req.append(EvidenceRequirement.TEST_IN_DOMAIN)
        req.append(EvidenceRequirement.ENDPOINT_SCOPE_MATCHES_CLAIM)

        seen: set[EvidenceRequirement] = set()
        return [r for r in req if not (r in seen or seen.add(r))]


# --- the claim ----------------------------------------------------------------


class Claim(BaseModel):
    """One testable assertion, fully typed and self-describing.

    `acceptance_policy` is optional at the schema level so a partially extracted
    claim can exist and be inspected — but a claim with no policy is not
    adjudicable. Use `crucible.claims.policy.ensure_policy` to fill it, or
    `is_adjudicable` to gate.
    """

    claim_id: str
    type: ClaimType = ClaimType.COMPARATIVE
    statement: Statement
    context: ClaimContext = Field(default_factory=ClaimContext)
    reported: ReportedValues = Field(default_factory=ReportedValues)
    acceptance_policy: AcceptancePolicy | None = None
    source: SourceRef | None = Field(default=None, description="where in the paper this came from")
    confidence: float = Field(0.0, ge=0.0, le=1.0, description="extraction confidence")
    notes: str | None = None

    @property
    def is_comparative(self) -> bool:
        return self.type in (ClaimType.COMPARATIVE, ClaimType.ABLATION, ClaimType.RANKING)

    @property
    def metric(self) -> str | None:
        """The metric the claim is in, preferring the margin's own metric."""
        if self.statement.margin and self.statement.margin.metric:
            return self.statement.margin.metric
        return self.reported.metric

    def is_adjudicable(self) -> tuple[bool, str | None]:
        """`(ok, reason)` — the structural preconditions for a verdict. Mirrors
        "no positive control, no verdict": a claim missing its policy, its
        comparator, or any measured number cannot be adjudicated, and saying so
        up front is cheaper than discovering it after execution."""
        if self.acceptance_policy is None:
            return False, "no_acceptance_policy"
        if self.is_comparative and not self.statement.comparator:
            return False, "comparative_claim_without_comparator"
        if self.metric is None:
            return False, "no_metric_named"
        if self.reported.subject_value is None and not self.reported.per_seed:
            return False, "no_reported_value"
        if self.is_comparative and self.reported.comparator_value is None \
                and not self.reported.per_seed:
            return False, "no_comparator_value"
        return True, None

    def requirements(self) -> list[EvidenceRequirement]:
        """Evidence requirements implied by this claim under its policy. Empty
        when no policy is attached (the claim is not adjudicable)."""
        if self.acceptance_policy is None:
            return []
        return self.acceptance_policy.requirements(self)


class ClaimSet(BaseModel):
    """What intake emits: the claims found, plus the provenance of the sources
    they came from and anything the extractor could not resolve."""

    title: str | None = None
    claims: list[Claim] = Field(default_factory=list)
    datasets: list[DatasetRef] = Field(default_factory=list)
    paper_path: str | None = None
    repo_root: str | None = None
    notes: str | None = None

    def adjudicable(self) -> list[Claim]:
        return [c for c in self.claims if c.is_adjudicable()[0]]

    def blocked(self) -> list[tuple[Claim, str]]:
        out: list[tuple[Claim, str]] = []
        for c in self.claims:
            ok, reason = c.is_adjudicable()
            if not ok and reason is not None:
                out.append((c, reason))
        return out
