"""Experiment Spec — the declarative input (design §4.1).

A statement of what to run and what would count as success. Authored by a human,
an upstream agent, or generated by Crucible's intake from a paper + repo.

Design rules enforced elsewhere but anchored here:
  - No positive control, no verdict. Intake must generate one if absent.
  - Tolerances are explicit and stored. "Reproduced" is never a vibe.
  - Budgets are hard.
"""

from __future__ import annotations

from pydantic import BaseModel, Field

from .enums import HypothesisType, ToleranceType


class Tolerance(BaseModel):
    type: ToleranceType = ToleranceType.ABSOLUTE
    value: float = Field(..., description="|observed - reported| within this = reproduced")


class Hypothesis(BaseModel):
    statement: str
    type: HypothesisType


class Source(BaseModel):
    repo_uri: str
    commit: str | None = Field(
        default=None, description="Pinned commit; intake pins this if absent."
    )
    paper_uri: str | None = None


class ClaimUnderTest(BaseModel):
    claim_id: str
    metric: str
    comparison: str = Field(..., description="e.g. 'method_x > baseline_b'")
    reported_values: dict[str, float] = Field(default_factory=dict)
    tolerance: Tolerance
    seeds: list[int] = Field(default_factory=lambda: [0, 1, 2])


class PositiveControl(BaseModel):
    """MUST pass before any verdict on claims (design §4.1, §8.1)."""

    control_id: str
    description: str
    metric: str
    expected: float
    tolerance: Tolerance


class Budget(BaseModel):
    max_wall_hours: float = 12.0
    max_cost_usd: float = 40.0
    max_repair_attempts_per_step: int = 3


class ScalePolicy(BaseModel):
    smoke_first: bool = True
    smoke_config: dict[str, object] = Field(
        default_factory=lambda: {"epochs": 1, "subset_fraction": 0.05}
    )


class GpuConstraint(BaseModel):
    required: bool = False
    min_memory_gb: int | None = None


class EnvironmentConstraints(BaseModel):
    gpu: GpuConstraint = Field(default_factory=GpuConstraint)


class ExperimentSpec(BaseModel):
    experiment_id: str
    hypothesis: Hypothesis
    source: Source
    claims_under_test: list[ClaimUnderTest] = Field(default_factory=list)
    positive_controls: list[PositiveControl] = Field(default_factory=list)
    budget: Budget = Field(default_factory=Budget)
    scale_policy: ScalePolicy = Field(default_factory=ScalePolicy)
    environment_constraints: EnvironmentConstraints = Field(
        default_factory=EnvironmentConstraints
    )

    def has_positive_control(self) -> bool:
        return len(self.positive_controls) > 0
